<a href="https://colab.research.google.com/github/xainse/ml-internship/blob/main/Onix_Internship%2C_ML_Lesson_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Home work for the lesson 07

In [75]:
import numpy as np

# Class*Class*Class*Class*Class*Class*Class*Class*Class*Class*Class*Class*
class MatrixUno:

  rowStartIndx = 0
  rowEndIndx = 1 
  colStartIndx = 2
  colEndIndx = 3

  # передаємо матрицю і зріз
  # проходжу по матриці і обнуляю все, що не входить в зріз по якимось умовам
  # виконую унарну операцію над всим масивом 
  # повертаю оброблений масив

  def abs(self, matrix, slice = None):
    #по умолчанию (если срез не задан) быстрые унарные математические операции выполняются над всеми элементами массива;
    if slice:
      matrix = self.set_zero( matrix, slice)

    matrix = np.sqrt(matrix)
    return matrix

  def sqrt(self, matrix, slice = None):
    #по умолчанию (если срез не задан) быстрые унарные математические операции выполняются над всеми элементами массива;
    if slice:
      matrix = self.set_zero( matrix, slice)

    matrix = np.sqrt(matrix)
    return matrix

  def square(self, matrix, slice = None):
    #по умолчанию (если срез не задан) быстрые унарные математические операции выполняются над всеми элементами массива;
    if slice:
      matrix = self.set_zero( matrix, slice)

    matrix = np.sqrt(matrix)
    return matrix

  def exp(self, matrix, slice = None):
    #по умолчанию (если срез не задан) быстрые унарные математические операции выполняются над всеми элементами массива;
    if slice:
      matrix = self.set_zero( matrix, slice)

    matrix = np.sqrt(matrix)
    return matrix

  def log(self, matrix, slice = None):
    if slice:
      matrix = self.set_zero( matrix, slice)
    return matrix

  def log10(self, matrix, slice = None):
    if slice:
      matrix = self.set_zero( matrix, slice)
    matrix = np.log10(matrix)
    return matrix

  def sign (self, matrix, slice = None):
    if slice: 
      matrix = self.set_zero(matrix, slice)
    matrix = np.sign(matrix)
    return matrix
    

  def make_qube(self, matrix, repeats):
    #x = np.repeat(matrix, repeats, axis=0) - результат копіюється не так, як потрібно

    x = np.tile(matrix, (repeats, 1, 1))

    return x

  def set_zero (self, matrix, slice):
    x = 0
    y = 0

    for row in matrix:
      y = 0
      for i in row:
        if (x < slice[self.rowStartIndx] or x >= slice[self.rowEndIndx]) or (y < slice[self.colStartIndx] or y >= slice[self.colEndIndx]) :
          matrix[x][y] = 0
        y += 1
      x += 1
    return matrix

# EndClass*ClassEnd*ClassEnd*ClassEnd*ClassEnd*ClassEnd*ClassEnd*ClassEnd*ClassEnd

mu = MatrixUno()

# Set Zero Example - Check Slice

In [31]:
arr = np.array([[0, 2, 0, 5, 5, 1, 3, 1],
                [9, 7, 1, 2, 9, 2, 1, 1],
                [1, 0, 3, 0, 1, 2, 5, 8],
                [5, 6, 2, 9, 7, 3, 8, 1],
                [5, 2, 4, 2, 9, 2, 9, 5],
                [9, 1, 8, 4, 8, 6, 6, 7],
                [2, 1, 2, 2, 2, 9, 0, 0]])

print(arr[1:4, 0:5])

# check slice
data = mu.log(arr, [1, 4, 0, 5])
print('\n', data)

[[9 7 1 2 9]
 [1 0 3 0 1]
 [5 6 2 9 7]]

 [[0 0 0 0 0 0 0 0]
 [9 7 1 2 9 0 0 0]
 [1 0 3 0 1 0 0 0]
 [5 6 2 9 7 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [32]:

# abs
arr_1 = np.array([
                    [10, 20, 30.3449, 40, 50],
                    [11, 21, 31, 41, 51],
                    [12, 22, 32, 42, 52],
                    [13, 23, 33, 43, 53],
                    [14, 24, 34, 44, 54],
                    [15, 25, 35, 45, 55]])

data = mu.abs(arr_1)
print('ABS opperation')

data


ABS opperation


array([[3.16227766, 4.47213595, 5.50862052, 6.32455532, 7.07106781],
       [3.31662479, 4.58257569, 5.56776436, 6.40312424, 7.14142843],
       [3.46410162, 4.69041576, 5.65685425, 6.4807407 , 7.21110255],
       [3.60555128, 4.79583152, 5.74456265, 6.55743852, 7.28010989],
       [3.74165739, 4.89897949, 5.83095189, 6.63324958, 7.34846923],
       [3.87298335, 5.        , 5.91607978, 6.70820393, 7.41619849]])

# Abs operation on slice

In [33]:
slice = [1,4,0,3]
data = mu.abs(arr_1, slice)
print('ABS opperation with slice')

data


ABS opperation with slice


array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [3.31662479, 4.58257569, 5.56776436, 0.        , 0.        ],
       [3.46410162, 4.69041576, 5.65685425, 0.        , 0.        ],
       [3.60555128, 4.79583152, 5.74456265, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

In [17]:
# square
arr_2 = np.random.rand(6, 7)
data = mu.square(arr_2, [3,4, 2,5])
data

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.42252131, 0.56978371, 0.65551533,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ]])

In [ ]:
arr_2 = np.random.rand(7, 5)
data = mu.square(arr_2, [3,4, 2,5])
data

In [35]:
# exp

arr_1 = np.random.rand(6, 7)
arr_1 = mu.exp(arr_1, [4, 6, 5, 7])

arr_1

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.77468763, 0.66442398],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.48234096, 0.70255248]])

In [41]:
# log10

arr = np.random.rand(5, 5)
arr = mu.log10(arr, [0, 2, 1, 4])

arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:56: RuntimeWarning: divide by zero encountered in log10


array([[       -inf, -0.17742008, -0.34824273, -0.28201085,        -inf],
       [       -inf, -0.49931817, -0.09882767, -0.1191824 ,        -inf],
       [       -inf,        -inf,        -inf,        -inf,        -inf],
       [       -inf,        -inf,        -inf,        -inf,        -inf],
       [       -inf,        -inf,        -inf,        -inf,        -inf]])

In [43]:
# sign
arr = np.random.rand(5, 5)
arr = mu.sign(arr, [2, 4, 1, 4])

arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

Перетворити вхідний двувимірний масив в трьохвимірний, копіюючи вхідний двухвимірний масив вздовж осі (axis=2)

In [77]:
arr = np.array([[7, -10],[3, 5]])
data = mu.make_qube(arr, 4)

print(data)


[[[  7 -10]
  [  3   5]]

 [[  7 -10]
  [  3   5]]

 [[  7 -10]
  [  3   5]]

 [[  7 -10]
  [  3   5]]]
